### ISSUE TITLE
Problem integrating Branch SDK

### ISSUE THREAD

**Issue by jonanderdev** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#122]
Hi! 
I have been having problems integrating the SDK.

I followed the steps indicated in the latest version of the README and of the website: https://dev.branch.io/recipes/quickstart_guide/android/

It worked in the Nexus 5  (Api Level 22) with no problems, but I cannot make it work in other phones like Samsung Galaxy S4 (Api Level 19). When starting the app I am getting the following exception:

```
java.lang.NoClassDefFoundError: io.branch.referral.Branch$SESSION_STATE
            at io.branch.referral.Branch.<init>(Branch.java:319)
            at io.branch.referral.Branch.initInstance(Branch.java:528)
            at io.branch.referral.Branch.getBranchInstance(Branch.java:431)
            at io.branch.referral.Branch.getTestInstance(Branch.java:482)
            at io.branch.referral.BranchApp.onCreate(BranchApp.java:37)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4581)
            at android.app.ActivityThread.access$1600(ActivityThread.java:161)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1325)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5356)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
            at dalvik.system.NativeStart.main(Native Method)
```

Do you know by chance which could be the reason to my problem?

Thanks in advance!

**Comment by sojanpr** [comment]
@jonanderdev We are sorry to hear that you have issue with branch integration.
From the log it seems like issue is that `Enum` class is not found. Can you please check whether you are excluding any .Class file  while creating your APK?
 Please let us know if this is not solving your issue.
Thanks

**Comment by jonanderdev** [comment]
Thanks for replying! At the end the problem was not related with Branch itself, but with the amount of methods of all the libraries my project was using, that was higher than the 65K limit. So I had to add MultiDex support.
Thanks for everything. Keep the good work!.

**Comment by sojanpr** [comment]
@jonanderdev  Thanks for the  confirmation

**Comment by apaunov** [comment]
Hello!

I seem to have a similar problem with my app. When I run my app (integrated with BranchIo) against Android 5.1.1 devices, the app works fine. However, when I test on Android 6.0.1 devices then I get the following exception (by the way, my app also includes the google play services lib in its project lib folder):

11-03 14:17:04.600: E/AndroidRuntime(2371): FATAL EXCEPTION: main 
11-03 14:17:04.600: E/AndroidRuntime(2371): Process: com.adesa.marketplace, PID: 2371 
11-03 14:17:04.600: E/AndroidRuntime(2371): java.lang.NoClassDefFoundError: io.branch.referral.BranchStrongMatchHelper$2 
11-03 14:17:04.600: E/AndroidRuntime(2371): at io.branch.referral.BranchStrongMatchHelper.checkForStrongMatch(BranchStrongMatchHelper.java:58) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at io.branch.referral.Branch.onIntentReady(Branch.java:2102) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at io.branch.referral.Branch.access$1100(Branch.java:70) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at io.branch.referral.Branch$BranchActivityLifeCycleObserver.onActivityResumed(Branch.java:2225) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.Application.dispatchActivityResumed(Application.java:214) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.Activity.onResume(Activity.java:1207) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:443) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at com.openlane.ui.activities.base.AbstractActivity.onResume(AbstractActivity.java:175) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at com.openlane.ui.activities.splash.SplashActivity.onResume(SplashActivity.java:89) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.Activity.performResume(Activity.java:6312) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.ActivityThread.-wrap11(ActivityThread.java) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.os.Handler.dispatchMessage(Handler.java:102) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.os.Looper.loop(Looper.java:148) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at android.app.ActivityThread.main(ActivityThread.java:5417) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at java.lang.reflect.Method.invoke(Native Method) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
11-03 14:17:04.600: E/AndroidRuntime(2371): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 

Since I am buying my app against ADT plugin in Eclipse I cannot use the easy setup in gradle which many people suggest on SO. I have tried to do some hacks in order to enable multidex support for Ant builds but I was not successful. Could you please advise on how to proceed?

Thank you!

**Comment by sojanpr** [comment]
@apaunov the problem seems to be with Multi dex. Can you please check the following in your project

1) Could you please make sure you are extending your "Application" class from "MultiDexApplicaiton" and have the following in your application class

@Override
protected void attachBaseContext(Context base) {
  super.attachBaseContext(base);
  MultiDex.install(this);
}
2. if the above not worked  Check the program settings and make sure `-dontoptimize `setting is enabled . Here is the document how to do program setting to get around this issue
http://proguard.sourceforge.net/manual/troubleshooting.html#invalidclassexception1

**Comment by sojanpr** [comment]
@apaunov Since you are using Eclipse and ADT plugin can you please try adding `dex.force.jumbo=true` in `project.properties` file

**Comment by apaunov** [comment]
Hello Sojanpr,

We have decided to migrate to gradle builds and Android Studio on our next app release. Therefore, we had to exclude the branch lib from our code for now. I will try your suggestion of enabling multidex in gradle once we get there and I'll let you know if it works or not. This will happen early next year (January) as that is when we'll be making our next release. Currently, we are at the end of our QA cycle so it's too late for us to change the code at test again. Thank you for writing back to me. I'll keep this thread updated when we try the mutlidex in gradle. 

Thank you very much for your support!

- Andrey
