### ISSUE TITLE
Minor Enhacnement: Change name of module from "library" to something branch related

### ISSUE THREAD

**Issue by jt-gilkeson** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#171]
In android studio your Project lists the downloaded External Libraries:
crashlytics-2.5.3
facebook-android-sdk-4.5.0
gson-2.4
...
and then shows the branch sdk as:
library-1.10.1

it would be nicer if the library had a name indicating that it was the branch sdk

**Comment by sojanpr** [comment]
@jt-gilkeson  Thanks for suggesting this. We will change to more meaning full name in coming versions

**Comment by sojanpr** [comment]
@jt-gilkeson if change the library name, our partners need to change the grade dependency name in order to upgrade to newer versions of SDK. So unless they change the dependency they may not get the  updated versions. We would really like to name it as you suggested but seems like  existing users  will have  lot of confusion

**Comment by jt-gilkeson** [comment]
@sojanpr Wonder if you could publish on maven to both names?  i.e. publish to the "meaningful name" and also publish to "library" (to handle people who don't update their gradle)

**Comment by sojanpr** [comment]
@jt-gilkeson at this point we don't want to introduce a confusion for partners with having multiple artifacts in maven. Your suggestion is really valid and we will make the change some time later.So closing this issue for now. Thank you for your suggestion.
