### ISSUE TITLE
How do you know that your session is initialized when you use automatic session management?

### ISSUE THREAD

**Issue by pcompassion** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#188]
Branch.getAutoInstance() does `automatic session management` according to the doc.  

Does that mean I can use any of the branch functionality freely in any place of my code (in any activity)?

In older style, there's a BranchReferralInitListener which I could use to make sure branch is fully initialized.  

How can I tell Branch is initialized if I use the automatic session management?

**Comment by sojanpr** [comment]
@pcompassion With Automatic Session Management , Branch will initialize the session up on starting the he first activity. You can always use `Branch.getInstance()` method to access Branch instance and  use any Branch functionality. If session is not initialized when you call an API, Branch will automatically initialize the session and then execute your API call. (Exception is only for few synchronous call where Branch returns an error if session is not initialized).
        With auto session also you can use `BranchReferralInitListener` if you still want to make sure the session is initialized before you make a Branch API call.
   In order to get a faster response, could you please email your implementation questions  to support@branch.io? 
Thanks

**Comment by pcompassion** [comment]
Thank you
