### ISSUE TITLE
I want to add two links in the ShareSheetStyle part of branch io one of details of the post and second for the playstore link, how to do this in android ? Please help me as I am working on this since last week.

### ISSUE THREAD

**Issue by shrutika229** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#208]
final LinkProperties linkProperties = new LinkProperties()
.setChannel("facebook")
.setFeature("sharing")
.addControlParameter("id",""+id)
.addControlParameter("$desktop_url",share_link)
// .addControlParameter("$android_deeplink_path", "Download App -https://play.google.com/store/apps/details?id=com.clinate.clinate&hl=en");
.addControlParameter("$android_url1", share_link)
.addControlParameter("$android_url2", "Download APP -"+"https://play.google.com/store/apps/details?id=com.clinate.clinate&hl=en");

**Comment by sojanpr** [comment]
@shrutika229 Thanks for reaching out.  You can set a fallback url in branch dash board to redirect to play store in case app is not installed. Also you can add a specific fall back url to each link with `$fallback_url` 
       `.addControlParameter("$fallback_url","https://www.yoursite.com")`

Our support team is really  awesome and they can  help you if you have more questions on this.  In order to get a faster response could you please send your integration questions to support@branch.io

**Comment by sojanpr** [comment]
@shrutika229  Hope the above commented helped to solve the issue. Closing this since it is not an SDK issue
