### ISSUE TITLE
Only open default web page in case app is not opened

### ISSUE THREAD

**Issue by anticafe** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#210]
i follow [this example](https://github.com/Winghin2517/BranchIOTestDeepLink) to learn how to integrate Branch.io deeep link into Android app.

At first, I create a new [Branch.io app](https://dashboard.branch.io/#/settings/link) and make sure **Always try to open app** is checked, Also set up app scheme to **test://** and package to **com.example.myapplication** and default web page to **https://www.google.com/**. From debug log, Branch url is [https://bnc.lt/qyyh/4iU683D8Yq](https://bnc.lt/qyyh/4iU683D8Yq)

I notice when open this link from Chrome browser while my Android app is active, then Chrome will redirect into Android app. However if I close the Android app, then when open link in Chrome, it will redirect into default web page instead.

As I know in Android, when open deep link, Android app can be opened even that app hasn't been started yet. And I think Branch deep link should has the same behavior. Do I mis-configure anything?

**Comment by sojanpr** [comment]
@anticafe Thanks for reaching out. Branch is opens the app provides the deep link params even if the app is closed.At this point it seems like some configuration issue with the app since it works on other test apps.  
 It is highly recommend to take a look at the sample app proved by Branch with latest features 
https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/tree/master/Branch-SDK-TestBed

Our support team is really awesome and they can help you if you have more questions on this. In order to get a faster response could you please send your integration questions to support@branch.io
