### ISSUE TITLE
Hard tabs everywhere!

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Android-Deferred-Deep-Linking-SDK#81]
Stop using hard tabs. Replace all hard tabs with soft tabs (for Java and Android, that's 4 spaces).

**Comment by shortstuffsushi** [comment]
@SleeplessByte I think a large portion of us fully agree with you here. It is just the way it is now because of a bad start and then following the trend to maintain consistency. However, this should be done as a *separate* pull request, so that changes are separate from formatting, and it just hasn't been done yet. I'll leave a note for this to be done after the outstanding rework PR is merged.

**Comment by SleeplessByte** [comment]
It's exactly the reason why I left it intact.

**Comment by shortstuffsushi** [comment]
Fixed by #108.
